/* Warning: This file is generated by ..\tests/collate-test - do not modify directly! */
extern bool test_synonym1();
extern bool test_synonym2();
extern bool test_synonym3();
extern bool test_synonym4();
