/* Warning: This file is generated by ..\tests/collate-test - do not modify directly! */
extern bool test_queryterms1();
extern bool test_matchnothing1();
extern bool test_nearsubqueries1();
extern bool test_xor3();
extern bool test_loosephrase1();
extern bool test_loosenear1();
