/* Warning: This file is generated by ..\tests/collate-test - do not modify directly! */
extern bool test_utf8iterator1();
extern bool test_utf8iterator2();
extern bool test_unicode1();
extern bool test_caseconvert1();
extern bool test_caseconvert2();
extern bool test_utf8convert1();
extern bool test_unicodepredicates1();
