/* Warning: This file is generated by ..\tests/collate-test - do not modify directly! */
extern bool test_oldsortfunctor1();
extern bool test_oldsortfunctor2();
extern bool test_oldchangesorter1();
extern bool test_oldsortfunctorempty1();
